# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resnet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cyolov5.proto\x12\x06yolov5\"\x1b\n\x05Image\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"h\n\tDetection\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x12\n\nclass_name\x18\x06 \x01(\t\"3\n\nDetections\x12%\n\ndetections\x18\x01 \x03(\x0b\x32\x11.yolov5.Detection2B\n\rYoloV5Service\x12\x31\n\x0c\x44\x65tectObject\x12\r.yolov5.Image\x1a\x12.yolov5.Detectionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolov5_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_IMAGE']._serialized_start=24
  _globals['_IMAGE']._serialized_end=51
  _globals['_DETECTION']._serialized_start=53
  _globals['_DETECTION']._serialized_end=157
  _globals['_DETECTIONS']._serialized_start=159
  _globals['_DETECTIONS']._serialized_end=210
  _globals['_YOLOV5SERVICE']._serialized_start=212
  _globals['_YOLOV5SERVICE']._serialized_end=278
# @@protoc_insertion_point(module_scope)
