# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resnet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cresnet.proto\x12\x06resnet\"\x1b\n\x05Image\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"?\n\x14\x43lassificationResult\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x13\n\x0bprobability\x18\x02 \x01(\x02\x32M\n\rResNetService\x12<\n\rClassifyImage\x12\r.resnet.Image\x1a\x1c.resnet.ClassificationResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resnet_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_IMAGE']._serialized_start=24
  _globals['_IMAGE']._serialized_end=51
  _globals['_CLASSIFICATIONRESULT']._serialized_start=53
  _globals['_CLASSIFICATIONRESULT']._serialized_end=116
  _globals['_RESNETSERVICE']._serialized_start=118
  _globals['_RESNETSERVICE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
