# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: huggingface.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11huggingface.proto\x12\x0bhuggingface\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\";\n\x12TranslationRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x17\n\x0ftarget_language\x18\x02 \x01(\t\".\n\x0e\x43lassification\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\"\x14\n\x04Text\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1c\n\x08\x45ntities\x12\x10\n\x08\x65ntities\x18\x01 \x03(\t2\xab\x03\n\x0bTextService\x12\x45\n\x0c\x43lassifyText\x12\x18.huggingface.TextRequest\x1a\x1b.huggingface.Classification\x12;\n\x0cGenerateText\x12\x18.huggingface.TextRequest\x1a\x11.huggingface.Text\x12I\n\x16NamedEntityRecognition\x12\x18.huggingface.TextRequest\x1a\x15.huggingface.Entities\x12\x43\n\rTranslateText\x12\x1f.huggingface.TranslationRequest\x1a\x11.huggingface.Text\x12J\n\x11SentimentAnalysis\x12\x18.huggingface.TextRequest\x1a\x1b.huggingface.Classification\x12<\n\rSummarizeText\x12\x18.huggingface.TextRequest\x1a\x11.huggingface.Textb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'huggingface_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TEXTREQUEST']._serialized_start=34
  _globals['_TEXTREQUEST']._serialized_end=61
  _globals['_TRANSLATIONREQUEST']._serialized_start=63
  _globals['_TRANSLATIONREQUEST']._serialized_end=122
  _globals['_CLASSIFICATION']._serialized_start=124
  _globals['_CLASSIFICATION']._serialized_end=170
  _globals['_TEXT']._serialized_start=172
  _globals['_TEXT']._serialized_end=192
  _globals['_ENTITIES']._serialized_start=194
  _globals['_ENTITIES']._serialized_end=222
  _globals['_TEXTSERVICE']._serialized_start=225
  _globals['_TEXTSERVICE']._serialized_end=652
# @@protoc_insertion_point(module_scope)
